### ISSUE TITLE
Incomplete Files Uploded

### ISSUE THREAD

**Issue by pranavdaa** [nhatminh12369/etherchat#3]
some major files including **index.html**  and some basic discretion to start the app are not provided.

**Comment by bitcoin4cashqc** [comment]
All files seems there...

**Comment by pranavdaa** [comment]
Then how to run the app.

**Comment by bitcoin4cashqc** [comment]
In the directory you cloned:

npm install
npm build
npm run

Check package.json!

**Comment by V2-Kumar** [comment]
App is not running. Anyone know how to run???

**Comment by FXartist** [comment]
This is the error I get:

This relative module was not found:

* ../ethereum/build/EtherChat.json in ./core/ContractManager.js
{ Error: Cannot find module '../ethereum/build/EtherChat.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (../core/ContractManager.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (../node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (../core/AppManager.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (../node_modules/source-map-support/source-map-support.js:492:25) code: 'MODULE_NOT_FOUND' }

**Comment by FXartist** [comment]
Files are all complete. Thank you
