### ISSUE TITLE
Error: Cannot find module '../ethereum/build/EtherChat.json'

### ISSUE THREAD

**Issue by FXartist** [nhatminh12369/etherchat#4]
This is the error I get while running $npm run dev

_This relative module was not found:

* ../ethereum/build/EtherChat.json in ./core/ContractManager.js
{ Error: Cannot find module '../ethereum/build/EtherChat.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (../core/ContractManager.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (../node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (../core/AppManager.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (../node_modules/source-map-support/source-map-support.js:492:25) code: 'MODULE_NOT_FOUND' }_

**Comment by nhatminh12369** [comment]
Hi there,

You need to compile the contract first. You can do that by going to root folder of the project and run:
"node ./ethereum/compile.js"

Then, you can run:
"npm run dev"

and go to the link appears in the console. (probably: http://localhost:3213/)

Hope that helps.

**Comment by FXartist** [comment]
That was it! I am sure I will have more questions for you as I dig it more. Meanwhile THANK YOU very much.
